### ISSUE TITLE
Found out one color

### ISSUE THREAD

**Issue by Entropy159** [edelkas/npc-web#4]
Turns out that the level editor has little letters for each entity, and the color is the same as the mini (eyebat) eye color. By the way, the game doesn't actually use that color for the mini drone.

**Comment by edelkas** [comment]
Nice find, added in 977f5df. As for the mini eye color, it is actually obtained by combining the color of the eye and the color of the mini background, though I don't recall what's the exact way in which they are combined.

For example, say the background is red. If the eye is white, then it'll appear white, if it's black, it'll appear red, and if it's anything in between, then you get an intermediate result (e.g., if it's green, then the eye becomes yellow). Added a note in the text explanation as well.
